http:
  port:"8080"

sfdc:
  username: "sirimalla.anusha@wipro.com"
  password: "Anusha@22"
  token: "9ZAW1wzRg6NLZqac5OPpopyzk"
  
file:
  accountsDir: "C:/anypoint/APDevFundamentals4.3_studentFiles_SP_29apr2021/APDevFundamentals4.3_studentFiles_SP_29apr2021/resources"
  
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"